minimumGradleVersion: 7.5.1
jacocoVersion: 0.8.8

defaultDependencies:
  - groupId: com.fasterxml.jackson
    artifactId: jackson-bom
    version: 2.14.2
  - groupId: com.google.guava
    artifactId: guava
    version: 31.1-jre
  - groupId: org.assertj
    artifactId: assertj-core
    version: 3.24.2
  - groupId: org.junit
    artifactId: junit-bom
    version: 5.9.2
  # 2.x does not support Java 8
  - groupId: org.junit-pioneer
    artifactId: junit-pioneer
    version: 1.9.1
  # 5.x does not support Java 8
  - groupId: org.mockito
    artifactId: mockito-bom
    version: 4.11.0
  - groupId: org.projectlombok
    artifactId: lombok
    version: 1.18.26

platformDependencies:
  - groupId: com.fasterxml.jackson
    artifactId: jackson-bom
  - groupId: org.junit
    artifactId: junit-bom
  - groupId: org.mockito
    artifactId: mockito-bom

testDependencies:
  - groupId: org.junit.jupiter
    artifactId: junit-jupiter
  - groupId: org.junit-pioneer
    artifactId: junit-pioneer
  - groupId: org.mockito
    artifactId: mockito-core
  - groupId: org.mockito
    artifactId: mockito-junit-jupiter
  - groupId: org.assertj
    artifactId: assertj-core

springTestDependencies:
  - groupId: org.springframework.boot
    artifactId: spring-boot-starter-test

gradlePlugins:
  # Last known version built with Java 8 bytecode
  - groupId: com.diffplug.spotless
    artifactId: spotless-plugin-gradle
    version: 6.13.0
  - groupId: org.springframework.boot
    artifactId: spring-boot-gradle-plugin
    version: 2.7.9
  # Spring Initializr recommendation for Spring Boot 2.7.9
  - groupId: io.spring.gradle
    artifactId: dependency-management-plugin
    version: 1.0.15.RELEASE
