minimumGradleVersion: 7.4.2
jacocoVersion: 0.8.8

defaultDependencies:
  - groupId: com.fasterxml.jackson
    artifactId: jackson-bom
    version: 2.13.3
  - groupId: com.google.guava
    artifactId: guava
    version: 31.1-jre
  - groupId: org.assertj
    artifactId: assertj-core
    version: 3.23.1
  - groupId: org.junit
    artifactId: junit-bom
    version: 5.8.2
  - groupId: org.junit-pioneer
    artifactId: junit-pioneer
    version: 1.7.1
  - groupId: org.mockito
    artifactId: mockito-bom
    version: 4.6.1
  - groupId: org.projectlombok
    artifactId: lombok
    version: 1.18.24

platformDependencies:
  - groupId: com.fasterxml.jackson
    artifactId: jackson-bom
  - groupId: org.junit
    artifactId: junit-bom
  - groupId: org.mockito
    artifactId: mockito-bom

testDependencies:
  - groupId: org.junit.jupiter
    artifactId: junit-jupiter
  - groupId: org.junit-pioneer
    artifactId: junit-pioneer
  - groupId: org.mockito
    artifactId: mockito-core
  - groupId: org.mockito
    artifactId: mockito-junit-jupiter
  - groupId: org.assertj
    artifactId: assertj-core

springTestDependencies:
  - groupId: org.springframework.boot
    artifactId: spring-boot-starter-test

gradlePlugins:
  - groupId: com.diffplug.spotless
    artifactId: spotless-plugin-gradle
    version: 6.7.2
  - groupId: org.springframework.boot
    artifactId: spring-boot-gradle-plugin
    version: 2.7.0
  - groupId: io.spring.gradle
    artifactId: dependency-management-plugin
    version: 1.0.11.RELEASE
