minimumGradleVersion: 7.6.1
jacocoVersion: 0.8.9

defaultDependencies:
  - groupId: com.fasterxml.jackson
    artifactId: jackson-bom
    version: 2.14.2
  - groupId: com.google.guava
    artifactId: guava
    version: 31.1-jre
  - groupId: org.assertj
    artifactId: assertj-core
    version: 3.24.2
  - groupId: org.junit
    artifactId: junit-bom
    version: 5.9.2
  - groupId: org.junit-pioneer
    artifactId: junit-pioneer
    version: 2.0.1
  - groupId: org.mockito
    artifactId: mockito-bom
    version: 5.3.1
  - groupId: org.projectlombok
    artifactId: lombok
    version: 1.18.26

platformDependencies:
  - groupId: com.fasterxml.jackson
    artifactId: jackson-bom
  - groupId: org.junit
    artifactId: junit-bom
  - groupId: org.mockito
    artifactId: mockito-bom

testDependencies:
  - groupId: org.junit.jupiter
    artifactId: junit-jupiter
  - groupId: org.junit-pioneer
    artifactId: junit-pioneer
  - groupId: org.mockito
    artifactId: mockito-core
  - groupId: org.mockito
    artifactId: mockito-junit-jupiter
  - groupId: org.assertj
    artifactId: assertj-core

springTestDependencies:
  - groupId: org.springframework.boot
    artifactId: spring-boot-starter-test

gradlePlugins:
  - groupId: com.diffplug.spotless
    artifactId: spotless-plugin-gradle
    version: 6.18.0
  - groupId: org.springframework.boot
    artifactId: spring-boot-gradle-plugin
    version: 3.0.6
  # Spring Initializr recommendation for Spring Boot 2.7.9
  - groupId: io.spring.gradle
    artifactId: dependency-management-plugin
    version: 1.1.0
