minimumGradleVersion: 7.3.3
jacocoVersion: 0.8.7

defaultDependencies:
  - groupId: com.fasterxml.jackson
    artifactId: jackson-bom
    version: 2.13.1
  - groupId: com.google.guava
    artifactId: guava
    version: 31.0.1-jre
  - groupId: org.assertj
    artifactId: assertj-core
    version: 3.22.0
  - groupId: org.junit
    artifactId: junit-bom
    version: 5.8.2
  - groupId: org.projectlombok
    artifactId: lombok
    version: 1.18.22

platformDependencies:
  - groupId: com.fasterxml.jackson
    artifactId: jackson-bom
  - groupId: org.junit
    artifactId: junit-bom

testDependencies:
  - groupId: org.junit.jupiter
    artifactId: junit-jupiter
  - groupId: org.assertj
    artifactId: assertj-core

springTestDependencies:
  - groupId: org.springframework.boot
    artifactId: spring-boot-starter-test

gradlePlugins:
  - groupId: com.diffplug.spotless
    artifactId: spotless-plugin-gradle
    version: 6.2.1
  - groupId: org.springframework.boot
    artifactId: spring-boot-gradle-plugin
    version: 2.6.3
  - groupId: io.spring.gradle
    artifactId: dependency-management-plugin
    version: 1.0.11.RELEASE
